steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nice-height-287701/googleoidctest:v1', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nice-height-287701/googleoidctest:v1']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/googleoidctest
  - googleoidctest-sha256-1=gcr.io/nice-height-287701/googleoidctest:v1
  - -n
  - googleoidctest-ns
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=goni-gke'
options:
  machineType: 'N1_HIGHCPU_8' # HIGHCPU로 빌드 스피드 업
timeout: 1000s # 빌드 자체에 대한 타임 아웃
